// Package gd92 implements the GD-92/1003A/2.2 communications protocol
// for UK Fire Service Mobilising Systems.
//
// The GD92 protocol defines a store-and-forward messaging system where
// messages are wrapped in envelopes containing addressing, sequencing,
// and integrity information. Messages are transferred between nodes via
// Message Transfer Agents (MTAs) using a simple framed protocol.
//
// This package provides:
//   - Binary encoding/decoding of all GD92 data types
//   - Address encoding (brigade/node/port packed into 3 bytes)
//   - ESC-based run-length compression for string fields
//   - Envelope marshalling/unmarshalling with BCC verification
//   - All 40+ message type structs with marshal/unmarshal
//   - MTA-level framing and connection management (mta subpackage)
//
// This is a proof-of-concept implementation generated by Claude Code
// from the GD-92 specification PDF. It has not been tested against
// real fire service equipment.
package gd92
